### ISSUE TITLE
Best way to manipulate the :active atribute through loops?

### ISSUE THREAD

**Issue by ghost** [imfaber/vue-tasty-burgers#1]
Hi!

How can I use loops from computed properties to make the :active attribute reactive? It appears to not work when I'm doing :active="this.burgerState". Just getting "`Expected Boolean, got String with value "true"`" but works when I pass plain "true" or "false" values. Doesn't make sense to me that it's not reactive with the string of value "true" but just expects boolean? Perhaps I am missing something here.

**Comment by imfaber** [comment]
Hi @cibric 
The `active` prop is of type boolean.

Not sure what the type of this.burgerState is but you might want to replace it with a condition like `:active="this.burgerState === 'active'"`

Hope it helps
