### ISSUE TITLE
Feature request: Switch on/off rounded corners

### ISSUE THREAD

**Issue by selfagency** [imfaber/vue-tasty-burgers#12]
Thanks for your work on this.

I would love to have an option in the config options object or a prop on the component like:

```
{
  rounded: false;
}
```

or:

```
<tasty-burger-menu :rounded="false" />
```

to disable the rounded edges on the elements.

Thanks!

**Comment by imfaber** [comment]
Hi @selfagency 

That sounds like a good idea thanks.
I'll do it ASAP if nobody else steps up

**Comment by imfaber** [comment]
Hi @selfagency 

This has now been added to `v.1.2.2`
