### ISSUE TITLE
emphatic icon not displaying correctly

### ISSUE THREAD

**Issue by studio-sixtyeight** [imfaber/vue-tasty-burgers#2]
When using size: 's' or 'xs' in combination with buttonType: 'emphatic', the icon looks clipped in their both non-active and active state.
The xs version even only shows up two out of three bars.

When using other sizes, the initial icon looks okay but still there is clipping when active.

I haven't spotted this issue with other buttonTypes.

**Comment by imfaber** [comment]
Hi @nitras 

This should now be fixed in `v.1.2.2`
