### ISSUE TITLE
Version 1.1.6

### ISSUE THREAD

**Issue by dazuku** [imfaber/vue-tasty-burgers#5]
When I update to the version 1.1.6, webpack is throwing this error:
```ERROR in ./src/main.js
Module not found: Error: Can't resolve 'vue-tasty-burgers' in '/Users/danieldaza/projects/z-recruitment/src'
 @ ./src/main.js 9:0-55 29:8-25
 @ multi webpack-hot-middleware/client?reload=true&timeout=1000 ./src/main.js

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'vue-tasty-burgers/dist/vue-tasty-burgers.css' in '/Users/danieldaza/projects/z-recruitment/src'
 @ ./src/main.js 21:0-54
 @ multi webpack-hot-middleware/client?reload=true&timeout=1000 ./src/main.js
```

And I saw the files in `node_modules` and the folder `vue-tasty-burgers` only have three files
- LICENSE
- package.json
- README.md

I'm not sure if it was something with the PR I made or it's something with the way you make the release if I can help with something let me know

**Comment by imfaber** [comment]
Hi @dazuku 

I just tried cloning a fresh copy and it works for me. 
I assume you tried running `npm i`? if so could you try again after deleting `node_modules`?

**Comment by pniedzwiedzinski** [comment]
I have the same issue. It's strange but it looks like the latest release is empty 😆, I downloaded the package from npm (https://registry.npmjs.org/vue-tasty-burgers/-/vue-tasty-burgers-1.1.6.tgz) and it's empty. How do you deploy the package?

But what's more mysterious is that it worked on your machine!

**Comment by imfaber** [comment]
@dazuku , @pniedzwiedzinski 
Really sorry,
I had forgotten about rebuilding before publishing.
Could you please try with 1.1.7?

**Comment by imfaber** [comment]
@dazuku I think I misunderstood what you meant because of what you said about webpack.

Webpack is only used for development. 
You can run the docs locally by running `npm run start`.
That will start a dev server where you can develop and debug the component.

**Comment by dazuku** [comment]
oh got it, I just tested it 1.1.7 and it works great

**Comment by pniedzwiedzinski** [comment]
> @dazuku , @pniedzwiedzinski
> Really sorry,
> I had forgotten about rebuilding before publishing.
> Could you please try with 1.1.7?

Are you doing this manually? It would be easier if you use Github Actions.

**Comment by imfaber** [comment]
> Are you doing this manually? It would be easier if you use Github Actions.

I will surely add some workflow ASAP, thanks for your suggestion.
If you would like to contribute, please feel free to open a PR.
