### ISSUE TITLE
Whole css loaded

### ISSUE THREAD

**Issue by pniedzwiedzinski** [imfaber/vue-tasty-burgers#9]
In my app, I'm using one hamburger but all CSS, for all hamburger types, is loaded into the HTML. This CSS is not a lot but that doesn't seem right. I was thinking maybe to divide hamburgers into the separate components. This would make managing it very easily and code would be more readable.

I could work on this improvement.

**Comment by imfaber** [comment]
Hi @pniedzwiedzinski 

I like your proposal and it would be great if you could work on it.

Thanks a lot 😄

**Comment by imfaber** [comment]
Hi @pniedzwiedzinski 

As you may have noticed I merged your PR with some tweaks on top of it.
Now the CSS is no longer exported as `.css` file so JS can load the style for the selected burger type only.

Thanks a lot for your help and let me know if you spot anything wrong
